apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend
  labels:
    app: frontend

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: micro-frontend
        name: frontend
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always