apiVersion: apps/v1

kind: Service

metadata:
  name: frontend-service
  labels:
    app: frontend

spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80
    nodePort: 8080
    targetPort: 8080
    protocol: TCP
    name: http